### ISSUE TITLE
DBC todo

### ISSUE THREAD

**Issue by Sarjuuk** [Sarjuuk/tc-wiki#1]
* [ ] fill bare pages (3 / 246)
* [ ] link to dbcs from database pages
* [ ] batch create links to wow.tools (content) + wowdev.wiki (additional structure src)
* [ ] create localization doc page (explain more data types?)
